const dict = {
  appName: '5sosy',
  appSub: 'Your AI tutor',
  nav: {
    home: 'Home', subjects: 'Subjects', books: 'Books', plan: 'Plan',
    practice: 'Practice', oral: 'Oral', progress: 'Progress', settings: 'Settings',
    profile: 'Profile', signOut: 'Sign out', menu: 'Menu', close: 'Close'
  },
  cta: { start: 'Get started', next: 'Next', back: 'Back', save: 'Save', finish: 'Finish', skip: 'Skip', signIn: 'Sign in', signUp: 'Sign up' },
  auth: {
    title: 'Welcome to 5sosy',
    sub: 'Sign in to continue your plan and study streak.',
    google: 'Continue with Google',
    anon: 'Continue as guest',
    email: 'Email',
    password: 'Password',
    or: 'or'
  },
  home: {
    greet: 'Welcome back 👋',
    sub: 'What are we studying today?',
    intentPh: 'Tell me what you need to study today…',
    examples: [
      'Physics exam in 48 hours',
      "I don't get gas laws",
      'Review history chapter 2',
      'Chemistry — quantitative analysis'
    ],
    plan: "Today's plan",
    planSub: 'Built by the planner from your goal',
    weak: 'Concepts to revisit',
    streak: 'Streak',
    streakDay: 'days in a row',
    xp: 'XP',
    next: 'Upcoming exams',
    activity: '5sosy activity'
  },
  subjects: {
    title: 'Your subjects',
    sub: 'Each subject groups your books, chapters and weak concepts',
    mastery: 'Mastery',
    chapters: 'Chapters',
    chaptersDone: 'chapters done',
    books: 'Books',
    weak: 'Weak topics',
    week: 'min this week',
    last: 'Last topic',
    drill: 'Drill',
    openBooks: 'Open books',
    takeQuiz: 'Take quiz',
    allSubjects: 'All subjects',
    onlyTrack: 'My track only',
    none: 'No subjects yet — finish onboarding first.'
  },
  plan: {
    title: 'Your week plan',
    sub: "Generated by the planner — adapts as you go",
    today: 'Today',
    blocks: 'sessions',
    total: 'Total',
    done: 'Done',
    remaining: 'Left',
    regenerate: 'Regenerate plan',
    regenerating: 'Regenerating…',
    empty: 'No sessions on this day',
    addBlock: 'Add session',
    daySummary: 'Day summary',
    minutes: 'min',
    sessions: 'sessions'
  },
  books: {
    title: 'Your connected books',
    sub: 'Egypt MOE curriculum + your external books — indexed in Vertex AI',
    indexed: 'Indexed',
    processing: 'Processing',
    queued: 'Queued',
    chapters: 'chapters',
    pages: 'pages',
    publisher: 'Publisher',
    year: 'Year',
    lastOpened: 'Last opened',
    selected: 'book selected',
    selectedPlural: 'books selected',
    selectAll: 'Select all',
    clear: 'Clear',
    selectToBegin: 'Pick one or more books to begin',
    action: {
      chat: 'Chat',
      summarize: 'Summarize',
      explain: 'Explain — Egyptian',
      audio: 'Audio summary',
      quiz: 'Quiz',
      questions: 'Suggested questions'
    },
    actionSub: {
      chat: 'Ask anything about these books',
      summarize: 'Tight summary of the key chapters',
      explain: 'Explanation in Egyptian colloquial',
      audio: 'Play an audio walkthrough',
      quiz: '5-question quick check',
      questions: 'Most-asked ministerial Qs'
    },
    chatPh: 'Ask anything about the selected books…',
    addBook: 'Connect new book',
    filterAll: 'All books',
    filterIndexed: 'Indexed only',
    workingOn: 'Pedagogy agent working',
    resultReady: 'Result ready',
    panelHint: 'Routed across 5 agents — Pedagogy + Ingestion + Assessment + AV + Orchestrator',
    goToQuiz: 'Start the quiz'
  }
} as const;

export default dict;
