// Dynamic subjects constants generated from seeded_subjects_localized.json
export type HueId =
  | 'sky' | 'violet' | 'emerald' | 'amber' | 'rose'
  | 'indigo' | 'cyan' | 'stone' | 'fuchsia' | 'teal';

export const HUE: Record<HueId, { bg: string; text: string; border: string; dot: string }> = {
  sky:     { bg: 'bg-sky-50',     text: 'text-sky-700',     border: 'border-sky-200',     dot: 'bg-sky-500' },
  violet:  { bg: 'bg-violet-50',  text: 'text-violet-700',  border: 'border-violet-200',  dot: 'bg-violet-500' },
  emerald: { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-500' },
  amber:   { bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200',   dot: 'bg-amber-500' },
  rose:    { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-500' },
  indigo:  { bg: 'bg-indigo-50',  text: 'text-indigo-700',  border: 'border-indigo-200',  dot: 'bg-indigo-500' },
  cyan:    { bg: 'bg-cyan-50',    text: 'text-cyan-700',    border: 'border-cyan-200',    dot: 'bg-cyan-500' },
  stone:   { bg: 'bg-stone-50',   text: 'text-stone-700',   border: 'border-stone-200',   dot: 'bg-stone-500' },
  fuchsia: { bg: 'bg-fuchsia-50', text: 'text-fuchsia-700', border: 'border-fuchsia-200', dot: 'bg-fuchsia-500' },
  teal:    { bg: 'bg-teal-50',    text: 'text-teal-700',    border: 'border-teal-200',    dot: 'bg-teal-500' }
};

export type SubjectMetaItem = {
  ar: string;
  en: string;
  fr: string;
  de: string;
  es: string;
  it: string;
  zh: string;
  hue: HueId;
  glyph: string;
  tracks: string[];
  description: {
    ar: string;
    en: string;
    fr: string;
    de: string;
    es: string;
    it: string;
    zh: string;
  };
};

// Localized labels for the Thanaweya academic tracks. Subject docs store the raw
// track codes (sci_sci / sci_math / lit); UI must never render the raw code.
export const TRACK_LABELS: Record<string, { ar: string; en: string }> = {
  sci_sci:  { ar: 'علمي علوم',  en: 'Science' },
  sci_math: { ar: 'علمي رياضة', en: 'Mathematics' },
  lit:      { ar: 'أدبي',       en: 'Literary' },
};

// Safe accessor: SUBJECT_META is keyed by curated slugs, but subject ids can come
// from user data, mock plans, or the DB and may not have an entry. Reading
// `SUBJECT_META[slug].hue` directly throws when the slug is unknown — always go
// through this so callers get a complete object (slug echoed as the name).
export function metaFor(slug: string): SubjectMetaItem {
  const m = SUBJECT_META[slug];
  if (m) return m;
  return {
    ar: slug, en: slug, fr: slug, de: slug, es: slug, it: slug, zh: slug,
    hue: 'stone', glyph: '📚', tracks: [],
    description: { ar: '', en: '', fr: '', de: '', es: '', it: '', zh: '' },
  };
}

export const SUBJECT_META: Record<string, SubjectMetaItem> = {
  'agriculture_entrepreneurship': {
    ar: "مهارات الزراعة وريادة الاعمال",
    en: "Agriculture and Entrepreneurship",
    fr: "Agriculture et entrepreneuriat",
    de: "Landwirtschaft und Unternehmertum",
    es: "Agricultura y emprendimiento",
    it: "Agricoltura e imprenditorialità",
    zh: "农业与创业",
    hue: 'emerald',
    glyph: '🌱',
    tracks: [],
    description: {
      ar: "تعلم أساسيات الزراعة وتطبيق مفاهيم ريادة الأعمال فيها.",
      en: "Learning the basics of agriculture and applying entrepreneurship concepts to it.",
      fr: "Apprendre les bases de l'agriculture et y appliquer les concepts de l'entrepreneuriat.",
      de: "Grundlagen der Landwirtschaft erlernen und unternehmerische Konzepte darauf anwenden.",
      es: "Aprender los conceptos básicos de la agricultura y aplicarles conceptos de emprendimiento.",
      it: "Imparare le basi dell'agricoltura e applicarvi i concetti di imprenditorialità.",
      zh: "学习农业基础知识并将创业概念应用于其中。",
    }
  },
  'algebra_and_statistics': {
    ar: "الجبر والإحصاء",
    en: "Algebra and Statistics",
    fr: "Algèbre et statistiques",
    de: "Algebra und Statistik",
    es: "Álgebra y estadística",
    it: "Algebra e statistica",
    zh: "代数与统计学",
    hue: 'indigo',
    glyph: '📊',
    tracks: ['sci_math'],
    description: {
      ar: "دراسة المعادلات الرياضية وتحليل البيانات.",
      en: "Study of mathematical equations and data analysis.",
      fr: "Étude des équations mathématiques et de l'analyse de données.",
      de: "Studium mathematischer Gleichungen und Datenanalyse.",
      es: "Estudio de ecuaciones matemáticas y análisis de datos.",
      it: "Studio delle equazioni matematiche e dell'analisi dei dati.",
      zh: "学习数学方程和数据分析。",
    }
  },
  'antarah_ibn_shaddad_story': {
    ar: "قصة أبو الفوارس عنترة بن شداد",
    en: "The Story of Antarah ibn Shaddad",
    fr: "L'histoire d'Antarah ibn Shaddad",
    de: "Die Geschichte von Antarah ibn Shaddad",
    es: "La historia de Antarah ibn Shaddad",
    it: "La storia di Antarah ibn Shaddad",
    zh: "安塔拉·伊本·沙达德的故事",
    hue: 'rose',
    glyph: '⚔️',
    tracks: [],
    description: {
      ar: "دراسة أدبية لقصة الفارس والشاعر العربي الشهير عنترة بن شداد.",
      en: "A literary study of the story of the famous Arab knight and poet Antarah ibn Shaddad.",
      fr: "Une étude littéraire de l'histoire du célèbre chevalier et poète arabe Antarah ibn Shaddad.",
      de: "Eine literarische Studie über die Geschichte des berühmten arabischen Ritters und Dichters Antarah ibn Shaddad.",
      es: "Un estudio literario de la historia del famoso caballero y poeta árabe Antarah ibn Shaddad.",
      it: "Uno studio letterario della storia del famoso cavaliere e poeta arabo Antarah ibn Shaddad.",
      zh: "对著名阿拉伯骑士兼诗人安塔拉·伊本·沙达德故事的文学研究。",
    }
  },
  'applied_mathematics': {
    ar: "الرياضيات التطبيقية",
    en: "Applied Mathematics",
    fr: "Mathématiques appliquées",
    de: "Angewandte Mathematik",
    es: "Matemáticas aplicadas",
    it: "Matematica applicata",
    zh: "应用数学",
    hue: 'indigo',
    glyph: '⚙️',
    tracks: ['sci_math'],
    description: {
      ar: "استخدام الأساليب الرياضية لحل المشكلات في العلوم والهندسة.",
      en: "The use of mathematical methods to solve problems in science and engineering.",
      fr: "L'utilisation de méthodes mathématiques pour résoudre des problèmes en science et en ingénierie.",
      de: "Die Anwendung mathematischer Methoden zur Lösung von Problemen in Wissenschaft und Technik.",
      es: "El uso de métodos matemáticos para resolver problemas en ciencia e ingeniería.",
      it: "L'uso di metodi matematici per risolvere problemi in scienza e ingegneria.",
      zh: "利用数学方法解决科学和工程中的问题。",
    }
  },
  'applied_mathematics_2': {
    ar: "تطبيقات الرياضيات",
    en: "Applied Mathematics",
    fr: "Mathématiques appliquées",
    de: "Angewandte Mathematik",
    es: "Matemáticas aplicadas",
    it: "Matematica applicata",
    zh: "应用数学",
    hue: 'emerald',
    glyph: '🧮',
    tracks: ['sci_math'],
    description: {
      ar: "تطبيق المفاهيم الرياضية في حل المشكلات العملية.",
      en: "Applying mathematical concepts to solve practical problems.",
      fr: "Application des concepts mathématiques pour résoudre des problèmes pratiques.",
      de: "Anwendung mathematischer Konzepte zur Lösung praktischer Probleme.",
      es: "Aplicación de conceptos matemáticos para resolver problemas prácticos.",
      it: "Applicazione di concetti matematici per risolvere problemi pratici.",
      zh: "应用数学概念解决实际问题。",
    }
  },
  'arabic_calligraphy': {
    ar: "كراسة الخط العربى",
    en: "Arabic Calligraphy",
    fr: "Calligraphie arabe",
    de: "Arabische Kalligraphie",
    es: "Caligrafía árabe",
    it: "Calligrafia araba",
    zh: "阿拉伯书法",
    hue: 'stone',
    glyph: '✒️',
    tracks: [],
    description: {
      ar: "تعلم فنون وقواعد الخط العربي الأصيل.",
      en: "Learn the arts and rules of authentic Arabic calligraphy.",
      fr: "Apprenez les arts et les règles de la calligraphie arabe authentique.",
      de: "Lernen Sie die Kunst und Regeln der authentischen arabischen Kalligraphie.",
      es: "Aprende las artes y reglas de la auténtica caligrafía árabe.",
      it: "Impara le arti e le regole dell'autentica calligrafia araba.",
      zh: "学习正宗阿拉伯书法的艺术和规则。",
    }
  },
  'arabic_grammar_and_morphology': {
    ar: "القواعد الأساسية للنحو والصرف",
    en: "Arabic Grammar and Morphology",
    fr: "Grammaire et morphologie arabes",
    de: "Arabische Grammatik und Morphologie",
    es: "Gramática y morfología árabe",
    it: "Grammatica e morfologia araba",
    zh: "阿拉伯语语法与形态学",
    hue: 'amber',
    glyph: '📖',
    tracks: [],
    description: {
      ar: "دراسة قواعد اللغة العربية وبنية الكلمات.",
      en: "The study of Arabic language rules and word structure.",
      fr: "L'étude des règles de la langue arabe et de la structure des mots.",
      de: "Das Studium der arabischen Sprachregeln und Wortstruktur.",
      es: "El estudio de las reglas del idioma árabe y la estructura de las palabras.",
      it: "Lo studio delle regole della lingua araba e della struttura delle parole.",
      zh: "研究阿拉伯语语言规则和词汇结构。",
    }
  },
  'arabic_language': {
    ar: "اللغة العربية",
    en: "Arabic Language",
    fr: "Langue arabe",
    de: "Arabische Sprache",
    es: "Idioma árabe",
    it: "Lingua araba",
    zh: "阿拉伯语",
    hue: 'amber',
    glyph: '📖',
    tracks: [],
    description: {
      ar: "دراسة قواعد اللغة العربية والنصوص الأدبية.",
      en: "Study of Arabic grammar and literary texts.",
      fr: "Étude de la grammaire arabe et des textes littéraires.",
      de: "Studium der arabischen Grammatik und literarischer Texte.",
      es: "Estudio de la gramática árabe y textos literarios.",
      it: "Studio della grammatica araba e dei testi letterari.",
      zh: "学习阿拉伯语语法和文学文本。",
    }
  },
  'arabic_literature_story': {
    ar: "اللغة العربية القصة",
    en: "Arabic Storytelling",
    fr: "Littérature arabe (récit)",
    de: "Arabische Erzählkunst",
    es: "Narrativa árabe",
    it: "Narrativa araba",
    zh: "阿拉伯语故事",
    hue: 'amber',
    glyph: '📜',
    tracks: [],
    description: {
      ar: "تحليل ودراسة القصص المقررة في منهج اللغة العربية.",
      en: "Analysis and study of the stories included in the Arabic curriculum.",
      fr: "Analyse et étude des histoires incluses dans le programme d'arabe.",
      de: "Analyse und Studium der im Arabischlehrplan enthaltenen Geschichten.",
      es: "Análisis y estudio de las historias incluidas en el plan de estudios de árabe.",
      it: "Analisi e studio delle storie incluse nel programma di arabo.",
      zh: "分析和研究阿拉伯语课程中包含的故事。",
    }
  },
  'art_education': {
    ar: "التربية الفنية",
    en: "Art Education",
    fr: "Éducation artistique",
    de: "Kunsterziehung",
    es: "Educación artística",
    it: "Educazione artistica",
    zh: "艺术教育",
    hue: 'fuchsia',
    glyph: '🎨',
    tracks: [],
    description: {
      ar: "تنمية المهارات الإبداعية والفنية.",
      en: "Developing creative and artistic skills.",
      fr: "Développement des compétences créatives et artistiques.",
      de: "Entwicklung kreativer und künstlerischer Fähigkeiten.",
      es: "Desarrollo de habilidades creativas y artísticas.",
      it: "Sviluppo di abilità creative e artistiche.",
      zh: "培养创造力和艺术技能。",
    }
  },
  'biology': {
    ar: "الاحياء",
    en: "Biology",
    fr: "Biologie",
    de: "Biologie",
    es: "Biología",
    it: "Biologia",
    zh: "生物学",
    hue: 'emerald',
    glyph: '🧬',
    tracks: ['sci_sci', 'sci_math'],
    description: {
      ar: "دراسة الكائنات الحية والعمليات الحيوية.",
      en: "The study of living organisms and vital processes.",
      fr: "L'étude des organismes vivants et des processus vitaux.",
      de: "Das Studium lebender Organismen und lebenswichtiger Prozesse.",
      es: "El estudio de los organismos vivos y los procesos vitales.",
      it: "Lo studio degli organismi viventi e dei processi vitali.",
      zh: "研究生物体和生命过程。",
    }
  },
  'chemistry': {
    ar: "الكيمياء",
    en: "Chemistry",
    fr: "Chimie",
    de: "Chemie",
    es: "Química",
    it: "Chimica",
    zh: "化学",
    hue: 'emerald',
    glyph: '🧪',
    tracks: ['sci_sci', 'sci_math'],
    description: {
      ar: "دراسة المادة وخصائصها والتفاعلات الكيميائية.",
      en: "The study of matter, its properties, and chemical reactions.",
      fr: "L'étude de la matière, de ses propriétés et des réactions chimiques.",
      de: "Das Studium der Materie, ihrer Eigenschaften und chemischen Reaktionen.",
      es: "El estudio de la materia, sus propiedades y las reacciones químicas.",
      it: "Lo studio della materia, delle sue proprietà e delle reazioni chimiche.",
      zh: "研究物质及其性质和化学反应。",
    }
  },
  'christian_religious_education': {
    ar: "التربية الدينية المسيحية",
    en: "Christian Religious Education",
    fr: "Éducation religieuse chrétienne",
    de: "Christliche Religionslehre",
    es: "Educación religiosa cristiana",
    it: "Educazione religiosa cristiana",
    zh: "基督教宗教教育",
    hue: 'amber',
    glyph: '✝️',
    tracks: [],
    description: {
      ar: "دراسة المبادئ والقيم المسيحية.",
      en: "Study of Christian principles and values.",
      fr: "Étude des principes et des valeurs chrétiennes.",
      de: "Studium christlicher Prinzipien und Werte.",
      es: "Estudio de los principios y valores cristianos.",
      it: "Studio dei principi e dei valori cristiani.",
      zh: "学习基督教原则和价值观。",
    }
  },
  'citizenship_and_human_rights': {
    ar: "المواطنة وحقوق الإنسان",
    en: "Citizenship and Human Rights",
    fr: "Citoyenneté et droits de l'homme",
    de: "Staatsbürgerschaft und Menschenrechte",
    es: "Ciudadanía y derechos humanos",
    it: "Cittadinanza e diritti umani",
    zh: "公民身份与人权",
    hue: 'indigo',
    glyph: '⚖️',
    tracks: [],
    description: {
      ar: "دراسة مفاهيم المواطنة والأسس القانونية لحقوق الإنسان.",
      en: "Study of citizenship concepts and the legal foundations of human rights.",
      fr: "Étude des concepts de citoyenneté et des fondements juridiques des droits de l'homme.",
      de: "Studium der Konzepte von Staatsbürgerschaft und der rechtlichen Grundlagen der Menschenrechte.",
      es: "Estudio de los conceptos de ciudadanía y los fundamentos legales de los derechos humanos.",
      it: "Studio dei concetti di cittadinanza e dei fondamenti legali dei diritti umani.",
      zh: "研究公民身份概念及人权的法律基础。",
    }
  },
  'computer_science_ict': {
    ar: "الكمبيوتر وتكنولوجيا المعلومات والإتصالات",
    en: "Computer and ICT",
    fr: "Informatique et TIC",
    de: "Informatik und IKT",
    es: "Informática y TIC",
    it: "Informatica e TIC",
    zh: "计算机与信息通信技术",
    hue: 'sky',
    glyph: '💻',
    tracks: [],
    description: {
      ar: "دراسة أساسيات الحاسب الآلي وتكنولوجيا المعلومات والاتصالات.",
      en: "Study of computer fundamentals and information and communication technology.",
      fr: "Étude des fondamentaux de l'informatique et des technologies de l'information et de la communication.",
      de: "Studium der Grundlagen der Informatik sowie Informations- und Kommunikationstechnik.",
      es: "Estudio de los fundamentos de la informática y las tecnologías de la información y la comunicación.",
      it: "Studio dei fondamenti dell'informatica e delle tecnologie dell'informazione e della comunicazione.",
      zh: "学习计算机基础知识以及信息与通信技术。",
    }
  },
  'development_geography': {
    ar: "جغرافيا التنمية",
    en: "Development Geography",
    fr: "Géographie du développement",
    de: "Entwicklungsgeographie",
    es: "Geografía del desarrollo",
    it: "Geografia dello sviluppo",
    zh: "发展地理学",
    hue: 'teal',
    glyph: '🌍',
    tracks: ['lit'],
    description: {
      ar: "دراسة التوزيع الجغرافي للموارد وعمليات التنمية الاقتصادية.",
      en: "Study of the geographical distribution of resources and economic development processes.",
      fr: "Étude de la répartition géographique des ressources et des processus de développement économique.",
      de: "Studium der geografischen Verteilung von Ressourcen und wirtschaftlichen Entwicklungsprozessen.",
      es: "Estudio de la distribución geográfica de los recursos y los procesos de desarrollo económico.",
      it: "Studio della distribuzione geografica delle risorse e dei processi di sviluppo economico.",
      zh: "研究资源的空间分布与经济发展过程。",
    }
  },
  'discover': {
    ar: "اكتشف",
    en: "Discover",
    fr: "Découvrir",
    de: "Entdecken",
    es: "Descubrir",
    it: "Scoprire",
    zh: "探索",
    hue: 'sky',
    glyph: '🔍',
    tracks: [],
    description: {
      ar: "مادة استكشافية لتنمية مهارات التفكير والبحث.",
      en: "An exploratory subject to develop thinking and research skills.",
      fr: "Une matière exploratoire pour développer les compétences de réflexion et de recherche.",
      de: "Ein exploratives Fach zur Entwicklung von Denk- und Forschungskompetenzen.",
      es: "Una asignatura exploratoria para desarrollar habilidades de pensamiento e investigación.",
      it: "Una materia esplorativa per sviluppare capacità di pensiero e ricerca.",
      zh: "一门旨在培养思维和研究能力的探索性学科。",
    }
  },
  'educational_media': {
    ar: "الاعلام التربوى",
    en: "Educational Media",
    fr: "Médias éducatifs",
    de: "Bildungsmedien",
    es: "Medios educativos",
    it: "Media educativi",
    zh: "教育媒体",
    hue: 'violet',
    glyph: '📺',
    tracks: [],
    description: {
      ar: "استخدام الوسائل الإعلامية في العملية التعليمية.",
      en: "The use of media tools in the educational process.",
      fr: "L'utilisation d'outils médiatiques dans le processus éducatif.",
      de: "Die Nutzung von Medienwerkzeugen im Bildungsprozess.",
      es: "El uso de herramientas mediáticas en el proceso educativo.",
      it: "L'uso di strumenti mediatici nel processo educativo.",
      zh: "在教育过程中使用媒体工具。",
    }
  },
  'english_language': {
    ar: "اللغة الانجليزية",
    en: "English Language",
    fr: "Langue anglaise",
    de: "Englische Sprache",
    es: "Idioma inglés",
    it: "Lingua inglese",
    zh: "英语",
    hue: 'indigo',
    glyph: '🇬🇧',
    tracks: [],
    description: {
      ar: "تطوير مهارات القراءة والكتابة والاستماع في اللغة الإنجليزية.",
      en: "Developing reading, writing, and listening skills in English.",
      fr: "Développement des compétences en lecture, écriture et écoute en anglais.",
      de: "Entwicklung von Lese-, Schreib- und Hörfähigkeiten in Englisch.",
      es: "Desarrollo de habilidades de lectura, escritura y escucha en inglés.",
      it: "Sviluppo delle abilità di lettura, scrittura e ascolto in inglese.",
      zh: "培养英语阅读、写作和听力技能。",
    }
  },
  'english_language_advanced': {
    ar: "اللغة الانجليزية مستوى رفيع",
    en: "Advanced English",
    fr: "Anglais avancé",
    de: "Englisch fortgeschritten",
    es: "Inglés avanzado",
    it: "Inglese avanzato",
    zh: "高级英语",
    hue: 'indigo',
    glyph: '📚',
    tracks: [],
    description: {
      ar: "دراسة متقدمة للأدب واللغة الإنجليزية.",
      en: "Advanced study of English literature and language.",
      fr: "Étude avancée de la littérature et de la langue anglaises.",
      de: "Fortgeschrittenes Studium der englischen Literatur und Sprache.",
      es: "Estudio avanzado de literatura y lengua inglesa.",
      it: "Studio avanzato della letteratura e della lingua inglese.",
      zh: "英语文学与语言的高级研究。",
    }
  },
  'family_management_entrepreneurship': {
    ar: "مهارات إدارة الأسرة و ريادة الأعمال",
    en: "Family Management and Entrepreneurship",
    fr: "Gestion familiale et entrepreneuriat",
    de: "Familienmanagement und Unternehmertum",
    es: "Gestión familiar y emprendimiento",
    it: "Gestione familiare e imprenditorialità",
    zh: "家庭管理与创业",
    hue: 'rose',
    glyph: '🏠',
    tracks: [],
    description: {
      ar: "تطوير مهارات إدارة شؤون الأسرة ومبادئ ريادة الأعمال.",
      en: "Developing skills for managing family affairs and principles of entrepreneurship.",
      fr: "Développement des compétences pour la gestion des affaires familiales et les principes de l'entrepreneuriat.",
      de: "Entwicklung von Fähigkeiten zur Führung von Familienangelegenheiten und Prinzipien des Unternehmertums.",
      es: "Desarrollo de habilidades para la gestión de asuntos familiares y principios de emprendimiento.",
      it: "Sviluppo di competenze per la gestione degli affari familiari e principi di imprenditorialità.",
      zh: "培养家庭事务管理技能和创业原则。",
    }
  },
  'first_language': {
    ar: "لغة أولى",
    en: "First Language",
    fr: "Première langue",
    de: "Erste Sprache",
    es: "Primera lengua",
    it: "Prima lingua",
    zh: "第一语言",
    hue: 'sky',
    glyph: '📖',
    tracks: [],
    description: {
      ar: "دراسة اللغة الأم وتطوير مهارات القراءة والكتابة.",
      en: "Study of the mother tongue and development of reading and writing skills.",
      fr: "Étude de la langue maternelle et développement des compétences en lecture et en écriture.",
      de: "Studium der Muttersprache und Entwicklung von Lese- und Schreibfähigkeiten.",
      es: "Estudio de la lengua materna y desarrollo de habilidades de lectura y escritura.",
      it: "Studio della lingua madre e sviluppo delle capacità di lettura e scrittura.",
      zh: "母语学习及读写能力的发展。",
    }
  },
  'french_language': {
    ar: "اللغة الفرنسية",
    en: "French Language",
    fr: "Langue française",
    de: "Französische Sprache",
    es: "Idioma francés",
    it: "Lingua francese",
    zh: "法语",
    hue: 'rose',
    glyph: '🇫🇷',
    tracks: [],
    description: {
      ar: "تعلم أساسيات اللغة الفرنسية ومهارات التواصل.",
      en: "Learning the basics of the French language and communication skills.",
      fr: "Apprentissage des bases de la langue française et des compétences de communication.",
      de: "Erlernen der Grundlagen der französischen Sprache und Kommunikationsfähigkeiten.",
      es: "Aprendizaje de los fundamentos del idioma francés y habilidades de comunicación.",
      it: "Apprendimento delle basi della lingua francese e delle abilità comunicative.",
      zh: "学习法语基础知识和沟通技巧。",
    }
  },
  'french_language_advanced': {
    ar: "لغة فرنسية مستوي رفيع",
    en: "Advanced French",
    fr: "Langue française niveau avancé",
    de: "Französische Sprache fortgeschrittenes Niveau",
    es: "Idioma francés nivel avanzado",
    it: "Lingua francese livello avanzato",
    zh: "法语高级水平",
    hue: 'sky',
    glyph: '📚',
    tracks: [],
    description: {
      ar: "منهج متقدم لتعزيز مهارات اللغة الفرنسية.",
      en: "An advanced curriculum to enhance French language skills.",
      fr: "Un programme avancé pour améliorer les compétences en langue française.",
      de: "Ein fortgeschrittener Lehrplan zur Verbesserung der französischen Sprachkenntnisse.",
      es: "Un plan de estudios avanzado para mejorar las habilidades en el idioma francés.",
      it: "Un programma avanzato per migliorare le competenze nella lingua francese.",
      zh: "旨在提高法语语言技能的高级课程。",
    }
  },
  'general_mathematics': {
    ar: "الرياضيات العامة",
    en: "General Mathematics",
    fr: "Mathématiques générales",
    de: "Allgemeine Mathematik",
    es: "Matemáticas generales",
    it: "Matematica generale",
    zh: "基础数学",
    hue: 'indigo',
    glyph: '➕',
    tracks: [],
    description: {
      ar: "مبادئ الرياضيات الأساسية المستخدمة في الحياة اليومية.",
      en: "Fundamental mathematical principles used in everyday life.",
      fr: "Principes mathématiques fondamentaux utilisés dans la vie quotidienne.",
      de: "Grundlegende mathematische Prinzipien für den Alltag.",
      es: "Principios matemáticos fundamentales utilizados en la vida cotidiana.",
      it: "Principi matematici fondamentali utilizzati nella vita quotidiana.",
      zh: "日常生活中使用的基础数学原理。",
    }
  },
  'geography': {
    ar: "الجغرافيا",
    en: "Geography",
    fr: "Géographie",
    de: "Geographie",
    es: "Geografía",
    it: "Geografia",
    zh: "地理",
    hue: 'emerald',
    glyph: '🌍',
    tracks: ['lit'],
    description: {
      ar: "دراسة الأرض ومعالمها وسكانها.",
      en: "Study of the Earth, its features, and inhabitants.",
      fr: "Étude de la Terre, de ses caractéristiques et de ses habitants.",
      de: "Studium der Erde, ihrer Merkmale und Bewohner.",
      es: "Estudio de la Tierra, sus características y habitantes.",
      it: "Studio della Terra, delle sue caratteristiche e dei suoi abitanti.",
      zh: "研究地球、其特征和居民。",
    }
  },
  'geometry_and_trigonometry': {
    ar: "الهندسة وحساب المثلثات",
    en: "Geometry and Trigonometry",
    fr: "Géométrie et trigonométrie",
    de: "Geometrie und Trigonometrie",
    es: "Geometría y trigonometría",
    it: "Geometria e trigonometria",
    zh: "几何与三角学",
    hue: 'emerald',
    glyph: '📐',
    tracks: ['sci_math'],
    description: {
      ar: "دراسة الأشكال الهندسية والعلاقات المثلثية.",
      en: "Study of geometric shapes and trigonometric relationships.",
      fr: "Étude des formes géométriques et des relations trigonométriques.",
      de: "Studium geometrischer Formen und trigonometrischer Beziehungen.",
      es: "Estudio de formas geométricas y relaciones trigonométricas.",
      it: "Studio delle forme geometriche e delle relazioni trigonometriche.",
      zh: "研究几何形状与三角关系。",
    }
  },
  'history': {
    ar: "التاريخ",
    en: "History",
    fr: "Histoire",
    de: "Geschichte",
    es: "Historia",
    it: "Storia",
    zh: "历史",
    hue: 'amber',
    glyph: '📜',
    tracks: ['lit'],
    description: {
      ar: "دراسة الأحداث الماضية وتطور المجتمعات البشرية.",
      en: "The study of past events and the development of human societies.",
      fr: "L'étude des événements passés et du développement des sociétés humaines.",
      de: "Das Studium vergangener Ereignisse und der Entwicklung menschlicher Gesellschaften.",
      es: "El estudio de los eventos pasados y el desarrollo de las sociedades humanas.",
      it: "Lo studio degli eventi passati e dello sviluppo delle società umane.",
      zh: "研究过去事件和人类社会的发展。",
    }
  },
  'home_economics': {
    ar: "الاقتصاد المنزلى",
    en: "Home Economics",
    fr: "Économie domestique",
    de: "Hauswirtschaft",
    es: "Economía doméstica",
    it: "Economia domestica",
    zh: "家政学",
    hue: 'rose',
    glyph: '🏠',
    tracks: [],
    description: {
      ar: "تعلم مهارات إدارة المنزل والحياة اليومية.",
      en: "Learning skills for home management and daily life.",
      fr: "Apprendre des compétences pour la gestion du foyer et la vie quotidienne.",
      de: "Erlernen von Fähigkeiten für die Haushaltsführung und das tägliche Leben.",
      es: "Aprender habilidades para la gestión del hogar y la vida diaria.",
      it: "Apprendere competenze per la gestione della casa e la vita quotidiana.",
      zh: "学习家庭管理和日常生活技能。",
    }
  },
  'ict': {
    ar: "تكنولوجيا المعلومات والاتصالات",
    en: "Information and Communication Technology",
    fr: "Technologies de l'information et de la communication",
    de: "Informations- und Kommunikationstechnologie",
    es: "Tecnologías de la información y la comunicación",
    it: "Tecnologie dell'informazione e della comunicazione",
    zh: "信息与通信技术",
    hue: 'cyan',
    glyph: '💻',
    tracks: [],
    description: {
      ar: "تعلم أساسيات الحاسب الآلي والشبكات والبرمجيات.",
      en: "Learning the basics of computers, networks, and software.",
      fr: "Apprendre les bases de l'informatique, des réseaux et des logiciels.",
      de: "Grundlagen der Informatik, Netzwerke und Software lernen.",
      es: "Aprender los conceptos básicos de computadoras, redes y software.",
      it: "Imparare le basi dell'informatica, delle reti e del software.",
      zh: "学习计算机、网络和软件的基础知识。",
    }
  },
  'industrial_skills_entrepreneurship': {
    ar: "مهارات الصناعة وريادة الأعمال",
    en: "Industrial Skills and Entrepreneurship",
    fr: "Compétences industrielles et entrepreneuriat",
    de: "Industrielle Fähigkeiten und Unternehmertum",
    es: "Habilidades industriales y emprendimiento",
    it: "Competenze industriali e imprenditorialità",
    zh: "工业技能与创业",
    hue: 'amber',
    glyph: '⚙️',
    tracks: [],
    description: {
      ar: "اكتساب المهارات الصناعية الأساسية ودمجها مع فكر ريادة الأعمال.",
      en: "Acquiring basic industrial skills and integrating them with entrepreneurial thinking.",
      fr: "Acquisition de compétences industrielles de base et intégration avec la pensée entrepreneuriale.",
      de: "Erwerb grundlegender industrieller Fähigkeiten und deren Integration in unternehmerisches Denken.",
      es: "Adquisición de habilidades industriales básicas e integración con el pensamiento emprendedor.",
      it: "Acquisizione di competenze industriali di base e integrazione con il pensiero imprenditoriale.",
      zh: "获取基础工业技能并将其与创业思维相结合。",
    }
  },
  'integrated_science': {
    ar: "العلوم المتكاملة",
    en: "Integrated Science",
    fr: "Sciences intégrées",
    de: "Integrierte Naturwissenschaften",
    es: "Ciencias integradas",
    it: "Scienze integrate",
    zh: "综合科学",
    hue: 'emerald',
    glyph: '🧬',
    tracks: ['sci_sci', 'sci_math'],
    description: {
      ar: "نهج متعدد التخصصات يجمع بين فروع العلوم المختلفة.",
      en: "A multidisciplinary approach combining various branches of science.",
      fr: "Une approche multidisciplinaire combinant diverses branches de la science.",
      de: "Ein multidisziplinärer Ansatz, der verschiedene Zweige der Wissenschaft kombiniert.",
      es: "Un enfoque multidisciplinario que combina varias ramas de la ciencia.",
      it: "Un approccio multidisciplinare che combina vari rami della scienza.",
      zh: "结合科学各分支的多学科方法。",
    }
  },
  'islamic_studies': {
    ar: "التربية الدينية الإسلامية",
    en: "Islamic Religious Education",
    fr: "Éducation religieuse islamique",
    de: "Islamischer Religionsunterricht",
    es: "Educación religiosa islámica",
    it: "Educazione religiosa islamica",
    zh: "伊斯兰宗教教育",
    hue: 'fuchsia',
    glyph: '☪️',
    tracks: [],
    description: {
      ar: "دراسة مبادئ وقيم الدين الإسلامي.",
      en: "The study of the principles and values of the Islamic religion.",
      fr: "L'étude des principes et des valeurs de la religion islamique.",
      de: "Das Studium der Prinzipien und Werte der islamischen Religion.",
      es: "El estudio de los principios y valores de la religión islámica.",
      it: "Lo studio dei principi e dei valori della religione islamica.",
      zh: "研究伊斯兰教的原则和价值观。",
    }
  },
  'library_and_research_skills': {
    ar: "المكتبات ومهارات البحث",
    en: "Library and Research Skills",
    fr: "Compétences en bibliothèque et recherche",
    de: "Bibliotheks- und Recherchekompetenzen",
    es: "Habilidades de biblioteca e investigación",
    it: "Competenze bibliotecarie e di ricerca",
    zh: "图书馆与研究技能",
    hue: 'stone',
    glyph: '🔍',
    tracks: [],
    description: {
      ar: "تعلم كيفية استخدام المكتبات وإجراء البحوث الأكاديمية بفعالية.",
      en: "Learn how to use libraries and conduct academic research effectively.",
      fr: "Apprenez à utiliser les bibliothèques et à mener des recherches académiques efficacement.",
      de: "Lernen Sie, wie man Bibliotheken nutzt und akademische Forschung effektiv durchführt.",
      es: "Aprenda a utilizar bibliotecas y realizar investigaciones académicas de manera efectiva.",
      it: "Impara a utilizzare le biblioteche e a condurre ricerche accademiche in modo efficace.",
      zh: "学习如何有效地利用图书馆并进行学术研究。",
    }
  },
  'maintenance_and_restoration': {
    ar: "الصيانة والترميمات",
    en: "Maintenance and Restoration",
    fr: "Maintenance et restauration",
    de: "Wartung und Restaurierung",
    es: "Mantenimiento y restauración",
    it: "Manutenzione e restauro",
    zh: "维护与修复",
    hue: 'stone',
    glyph: '🛠️',
    tracks: [],
    description: {
      ar: "تعلم مهارات إصلاح وصيانة المعدات والمباني.",
      en: "Learning skills for repairing and maintaining equipment and structures.",
      fr: "Apprentissage des compétences pour réparer et entretenir les équipements et les structures.",
      de: "Erlernen von Fähigkeiten zur Reparatur und Wartung von Geräten und Strukturen.",
      es: "Aprendizaje de habilidades para reparar y mantener equipos y estructuras.",
      it: "Apprendimento di competenze per riparare e mantenere attrezzature e strutture.",
      zh: "学习维修和保养设备及结构的技能。",
    }
  },
  'mathematics': {
    ar: "الرياضيات",
    en: "Mathematics",
    fr: "Mathématiques",
    de: "Mathematik",
    es: "Matemáticas",
    it: "Matematica",
    zh: "数学",
    hue: 'indigo',
    glyph: '📐',
    tracks: ['sci_math'],
    description: {
      ar: "دراسة الأعداد والكميات والأشكال والعلاقات.",
      en: "The study of numbers, quantities, shapes, and relationships.",
      fr: "L'étude des nombres, des quantités, des formes et des relations.",
      de: "Das Studium von Zahlen, Mengen, Formen und Beziehungen.",
      es: "El estudio de números, cantidades, formas y relaciones.",
      it: "Lo studio di numeri, quantità, forme e relazioni.",
      zh: "研究数字、数量、形状和关系。",
    }
  },
  'music_education': {
    ar: "التربية الموسيقية",
    en: "Music Education",
    fr: "Éducation musicale",
    de: "Musikerziehung",
    es: "Educación musical",
    it: "Educazione musicale",
    zh: "音乐教育",
    hue: 'violet',
    glyph: '🎵',
    tracks: [],
    description: {
      ar: "تعلم أساسيات الموسيقى والتذوق الفني.",
      en: "Learning music fundamentals and appreciation.",
      fr: "Apprentissage des bases de la musique et de l'appréciation artistique.",
      de: "Erlernen der Grundlagen der Musik und Musikverständnis.",
      es: "Aprendizaje de los fundamentos de la música y la apreciación artística.",
      it: "Apprendimento delle basi della musica e dell'apprezzamento artistico.",
      zh: "学习音乐基础知识和艺术鉴赏。",
    }
  },
  'national_education': {
    ar: "التربية الوطنية",
    en: "National Education",
    fr: "Éducation civique",
    de: "Staatsbürgerkunde",
    es: "Educación cívica",
    it: "Educazione civica",
    zh: "公民教育",
    hue: 'sky',
    glyph: '🇪🇬',
    tracks: [],
    description: {
      ar: "فهم الحقوق والواجبات الوطنية.",
      en: "Understanding national rights and duties.",
      fr: "Compréhension des droits et devoirs nationaux.",
      de: "Verständnis nationaler Rechte und Pflichten.",
      es: "Comprensión de los derechos y deberes nacionales.",
      it: "Comprensione dei diritti e dei doveri nazionali.",
      zh: "了解国家权利和义务。",
    }
  },
  'philosophy_and_logic': {
    ar: "الفلسفة والمنطق",
    en: "Philosophy and Logic",
    fr: "Philosophie et logique",
    de: "Philosophie und Logik",
    es: "Filosofía y lógica",
    it: "Filosofia e logica",
    zh: "哲学与逻辑",
    hue: 'violet',
    glyph: '🧠',
    tracks: ['lit'],
    description: {
      ar: "دراسة الأسئلة الأساسية حول الوجود والمعرفة والتفكير المنطقي.",
      en: "The study of fundamental questions about existence, knowledge, and logical reasoning.",
      fr: "L'étude des questions fondamentales sur l'existence, la connaissance et le raisonnement logique.",
      de: "Das Studium grundlegender Fragen zu Existenz, Wissen und logischem Denken.",
      es: "El estudio de preguntas fundamentales sobre la existencia, el conocimiento y el razonamiento lógico.",
      it: "Lo studio di domande fondamentali sull'esistenza, la conoscenza e il ragionamento logico.",
      zh: "研究关于存在、知识和逻辑推理的基本问题。",
    }
  },
  'physics': {
    ar: "الفيزياء",
    en: "Physics",
    fr: "Physique",
    de: "Physik",
    es: "Física",
    it: "Fisica",
    zh: "物理",
    hue: 'sky',
    glyph: '⚛️',
    tracks: ['sci_sci', 'sci_math'],
    description: {
      ar: "دراسة المادة والطاقة وتفاعلاتهما في الكون.",
      en: "The study of matter, energy, and their interactions in the universe.",
      fr: "L'étude de la matière, de l'énergie et de leurs interactions dans l'univers.",
      de: "Das Studium von Materie, Energie und deren Wechselwirkungen im Universum.",
      es: "El estudio de la materia, la energía y sus interacciones en el universo.",
      it: "Lo studio della materia, dell'energia e delle loro interazioni nell'universo.",
      zh: "研究宇宙中物质、能量及其相互作用。",
    }
  },
  'political_geography': {
    ar: "الجغرافيا السياسية",
    en: "Political Geography",
    fr: "Géographie politique",
    de: "Politische Geographie",
    es: "Geografía política",
    it: "Geografia politica",
    zh: "政治地理学",
    hue: 'teal',
    glyph: '🗺️',
    tracks: ['lit'],
    description: {
      ar: "دراسة تأثير الجغرافيا على السياسة الدولية.",
      en: "Study of the impact of geography on international politics.",
      fr: "Étude de l'impact de la géographie sur la politique internationale.",
      de: "Studium des Einflusses der Geographie auf die internationale Politik.",
      es: "Estudio del impacto de la geografía en la política internacional.",
      it: "Studio dell'impatto della geografia sulla politica internazionale.",
      zh: "研究地理对国际政治的影响。",
    }
  },
  'programming_and_ai': {
    ar: "البرمجة والذكاء الاصطناعى",
    en: "Programming and AI",
    fr: "Programmation et IA",
    de: "Programmierung und KI",
    es: "Programación e IA",
    it: "Programmazione e IA",
    zh: "编程与人工智能",
    hue: 'teal',
    glyph: '💻',
    tracks: [],
    description: {
      ar: "تعلم لغات البرمجة وأساسيات الذكاء الاصطناعي.",
      en: "Learning programming languages and the basics of artificial intelligence.",
      fr: "Apprendre les langages de programmation et les bases de l'intelligence artificielle.",
      de: "Erlernen von Programmiersprachen und den Grundlagen der künstlichen Intelligenz.",
      es: "Aprender lenguajes de programación y los fundamentos de la inteligencia artificial.",
      it: "Apprendere i linguaggi di programmazione e le basi dell'intelligenza artificiale.",
      zh: "学习编程语言和人工智能基础。",
    }
  },
  'psychology_and_sociology': {
    ar: "علم النفس والاجتماع",
    en: "Psychology and Sociology",
    fr: "Psychologie et sociologie",
    de: "Psychologie und Soziologie",
    es: "Psicología y sociología",
    it: "Psicologia e sociologia",
    zh: "心理学与社会学",
    hue: 'fuchsia',
    glyph: '🧠',
    tracks: ['lit'],
    description: {
      ar: "دراسة السلوك البشري والتفاعلات الاجتماعية في المجتمع.",
      en: "Study of human behavior and social interactions in society.",
      fr: "Étude du comportement humain et des interactions sociales dans la société.",
      de: "Studium des menschlichen Verhaltens und sozialer Interaktionen in der Gesellschaft.",
      es: "Estudio del comportamiento humano y las interacciones sociales en la sociedad.",
      it: "Studio del comportamento umano e delle interazioni sociali nella società.",
      zh: "研究人类行为与社会中的社会互动。",
    }
  },
  'pure_mathematics': {
    ar: "الرياضيات البحتة",
    en: "Pure Mathematics",
    fr: "Mathématiques pures",
    de: "Reine Mathematik",
    es: "Matemáticas puras",
    it: "Matematica pura",
    zh: "纯数学",
    hue: 'indigo',
    glyph: '🔢',
    tracks: ['sci_math'],
    description: {
      ar: "دراسة المفاهيم الرياضية المجردة بعيداً عن التطبيقات العملية.",
      en: "The study of abstract mathematical concepts independent of practical applications.",
      fr: "L'étude des concepts mathématiques abstraits indépendamment des applications pratiques.",
      de: "Das Studium abstrakter mathematischer Konzepte unabhängig von praktischen Anwendungen.",
      es: "El estudio de conceptos matemáticos abstractos independientes de aplicaciones prácticas.",
      it: "Lo studio di concetti matematici astratti indipendenti dalle applicazioni pratiche.",
      zh: "研究独立于实际应用的抽象数学概念。",
    }
  },
  'science': {
    ar: "العلوم",
    en: "Science",
    fr: "Science",
    de: "Wissenschaft",
    es: "Ciencia",
    it: "Scienza",
    zh: "科学",
    hue: 'emerald',
    glyph: '🔬',
    tracks: ['sci_sci', 'sci_math'],
    description: {
      ar: "دراسة العالم الطبيعي من خلال الملاحظة والتجريب.",
      en: "The study of the natural world through observation and experimentation.",
      fr: "L'étude du monde naturel par l'observation et l'expérimentation.",
      de: "Das Studium der natürlichen Welt durch Beobachtung und Experimente.",
      es: "El estudio del mundo natural a través de la observación y la experimentación.",
      it: "Lo studio del mondo naturale attraverso l'osservazione e la sperimentazione.",
      zh: "通过观察和实验研究自然世界。",
    }
  },
  'second_language': {
    ar: "لغة ثانية",
    en: "Second Language",
    fr: "Deuxième langue",
    de: "Zweite Sprache",
    es: "Segunda lengua",
    it: "Seconda lingua",
    zh: "第二语言",
    hue: 'indigo',
    glyph: '🗣️',
    tracks: [],
    description: {
      ar: "تعلم لغة أجنبية إضافية لتعزيز مهارات التواصل.",
      en: "Learning an additional foreign language to enhance communication skills.",
      fr: "Apprentissage d'une langue étrangère supplémentaire pour améliorer les compétences en communication.",
      de: "Erlernen einer zusätzlichen Fremdsprache zur Verbesserung der Kommunikationsfähigkeiten.",
      es: "Aprendizaje de un idioma extranjero adicional para mejorar las habilidades de comunicación.",
      it: "Apprendimento di una lingua straniera aggiuntiva per migliorare le capacità comunicative.",
      zh: "学习额外的外语以提高沟通技巧。",
    }
  },
  'social_studies': {
    ar: "الدراسات الإجتماعية",
    en: "Social Studies",
    fr: "Études sociales",
    de: "Sozialkunde",
    es: "Estudios sociales",
    it: "Studi sociali",
    zh: "社会研究",
    hue: 'stone',
    glyph: '🏛️',
    tracks: ['lit'],
    description: {
      ar: "دراسة المجتمع والتاريخ والجغرافيا.",
      en: "Study of society, history, and geography.",
      fr: "Étude de la société, de l'histoire et de la géographie.",
      de: "Studium von Gesellschaft, Geschichte und Geographie.",
      es: "Estudio de la sociedad, la historia y la geografía.",
      it: "Studio della società, della storia e della geografia.",
      zh: "研究社会、历史和地理。",
    }
  },
  'social_studies_alt': {
    ar: "الدراسات الاجتماعية",
    en: "Social Studies",
    fr: "Études sociales",
    de: "Sozialkunde",
    es: "Estudios sociales",
    it: "Studi sociali",
    zh: "社会研究",
    hue: 'stone',
    glyph: '🏛️',
    tracks: ['lit'],
    description: {
      ar: "دراسة المجتمع والتاريخ والجغرافيا.",
      en: "Study of society, history, and geography.",
      fr: "Étude de la société, de l'histoire et de la géographie.",
      de: "Studium von Gesellschaft, Geschichte und Geographie.",
      es: "Estudio de la sociedad, la historia y la geografía.",
      it: "Studio della società, della storia e della geografia.",
      zh: "研究社会、历史和地理。",
    }
  },
  'statistics': {
    ar: "الإحصاء",
    en: "Statistics",
    fr: "Statistiques",
    de: "Statistik",
    es: "Estadística",
    it: "Statistica",
    zh: "统计学",
    hue: 'indigo',
    glyph: '📊',
    tracks: ['sci_math'],
    description: {
      ar: "دراسة جمع وتحليل وتفسير البيانات الرقمية.",
      en: "The study of collecting, analyzing, and interpreting numerical data.",
      fr: "L'étude de la collecte, de l'analyse et de l'interprétation des données numériques.",
      de: "Das Studium der Sammlung, Analyse und Interpretation numerischer Daten.",
      es: "El estudio de la recopilación, el análisis y la interpretación de datos numéricos.",
      it: "Lo studio della raccolta, dell'analisi e dell'interpretazione dei dati numerici.",
      zh: "研究数字数据的收集、分析和解释。",
    }
  },
  'theater_education': {
    ar: "التربية المسرحية",
    en: "Theater Education",
    fr: "Éducation théâtrale",
    de: "Theaterpädagogik",
    es: "Educación teatral",
    it: "Educazione teatrale",
    zh: "戏剧教育",
    hue: 'rose',
    glyph: '🎭',
    tracks: [],
    description: {
      ar: "استكشاف فنون الأداء والتمثيل.",
      en: "Exploring performing arts and acting.",
      fr: "Exploration des arts du spectacle et du théâtre.",
      de: "Erkundung der darstellenden Künste und Schauspielerei.",
      es: "Exploración de las artes escénicas y la actuación.",
      it: "Esplorazione delle arti performative e della recitazione.",
      zh: "探索表演艺术和演戏。",
    }
  },
  'vocational_skills': {
    ar: "مهارات مهنية",
    en: "Vocational Skills",
    fr: "Compétences professionnelles",
    de: "Berufliche Fähigkeiten",
    es: "Habilidades vocacionales",
    it: "Competenze professionali",
    zh: "职业技能",
    hue: 'teal',
    glyph: '🛠️',
    tracks: [],
    description: {
      ar: "تطوير المهارات العملية والتقنية اللازمة لسوق العمل.",
      en: "Developing practical and technical skills necessary for the labor market.",
      fr: "Développement des compétences pratiques et techniques nécessaires au marché du travail.",
      de: "Entwicklung praktischer und technischer Fähigkeiten, die für den Arbeitsmarkt erforderlich sind.",
      es: "Desarrollo de habilidades prácticas y técnicas necesarias para el mercado laboral.",
      it: "Sviluppo di competenze pratiche e tecniche necessarie per il mercato del lavoro.",
      zh: "培养劳动力市场所需的实践和技术技能。",
    }
  },
};
